# FROM almalinux:9
# # CMD ["ping", "google.com"] cmd instruction can be overriden by cmd line arguments/inputs 
# ENTRYPOINT ["ping", "google.com"]  
# # entrypoint cannot be overriden by cmd line arguments

FROM almalinux:9
CMD ["google.com"]
ENTRYPOINT ["ping"] 
# entry point takes CMD as input and we can override CMD instruction with cmd lines arguments/inputs