FROM almalinux:9
ENV course="devops with aws" \
    trainer="siva kumar reddy" \
    duration="120hrs" \
    currentlearning="docker"
RUN echo "Hello ${trainer}" > /tmp/hello.txt
CMD ["sleep", "100"]
